### ISSUE TITLE
Misleading information in readme - the script can very much handle filenames with spaces

### ISSUE THREAD

**Issue by rluetzner** [oogg06/cbr2cbz#2]
Thank you very much for this script. I just wanted to chime in, that I could **not** observe any issues with spaces in filenames, even though the README claims the script cannot handle such files.

Here's how I used this to convert all cbr files in my Calibre library to cbz:

```bash
# 'fd' is pretty much the same as 'find'.
# I think 'find' uses '-print0' instead of '-0'.
fd cbr ~/Calibre-Bibliothek -0 | xargs -0 -I {} ./cbr2cbz.py {}
fd cbr ~/Calibre-Bibliothek -0 | xargs -0 -I {} rm {}
```

All files were converted successfully and the resulting filenames were the same as before. I did not encounter any errors. :slightly_smiling_face: 

After I ran 'rebuild Calibre database' from Calibre, it cleaned out the removed files and picked up the new cbz files perfectly.

I'm leaving this here, in case anybody else might find this useful.

Again, thank you very much for leaving your script here. :slightly_smiling_face:

**Comment by oogg06** [comment]
Yes, it's true. @nmorey fixed it and I forgot to update README. Thank you very much :)
